# Change these first
owner: Heat-Gaming
repo: stats

sites:
  - name: Server 1 | Roleplay
    url: https://sv1.heatgaming.net
    icon: https://cdn.heatgaming.net/icons/snails/sv1.ico
  - name: Server 2 | Drift/Freeroam
    url: https://sv2.heatgaming.net
    icon: https://cdn.heatgaming.net/icons/snails/sv2.ico
  - name: Server 1 | Miscellaneous 
    url: https://sv3.heatgaming.net
    icon: https://cdn.heatgaming.net/icons/snails/sv3.ico

status-website:
  cname: stats.heatgaming.net
  logoUrl: https://cdn.heatgaming.net/logos/logo_transparent-borderless.png
  favicon: https://cdn.heatgaming.net/logos/logo_transparent-borderless.png
  # themes: light, dark, night, or ocean.
  theme: night
  name: Heat Gaming
  introTitle: "**Heat Gaming Network**"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: Discord
      href: https://discord.gg/de3sXsX
  customHeadHtml: "<!-- Primary Meta Tags -->
                   <title>Heat Gaming Network Status</title>
                   <meta name="title" content="Heat Gaming Network Status">
                   <meta name="description" content="View The status of any server/services, as well as incident reports and updates, with live metrics straight from the servers.">
                   <!-- Open Graph / Facebook -->
                   <meta property="og:type" content="website">
                   <meta property="og:url" content="https://stats.heatgaming.net/">
                   <meta property="og:title" content="Heat Gaming Network Status">
                   <meta property="og:description" content="View The status of any server/services, as well as incident reports and updates, with live metrics straight from the servers.">
                   <meta property="og:image" content="https://cdn.heatgaming.net/logos/logo_transparent-borderless.png">
                   <!-- Twitter -->
                   <meta property="twitter:card" content="summary_large_image">
                   <meta property="twitter:url" content="https://stats.heatgaming.net/">
                   <meta property="twitter:title" content="Heat Gaming Network Status">
                   <meta property="twitter:description" content="View The status of any server/services, as well as incident reports and updates, with live metrics straight from the servers.">
                   <meta property="twitter:image" content="https://cdn.heatgaming.net/logos/logo_transparent-borderless.png">"

# https://upptime.js.org/docs/configuration