# Change these first
owner: Heat-Gaming
repo: stats

sites:
  - name: Server 1 | Roleplay
    url: https://sv1.heatgaming.net
    icon: https://cdn.heatgaming.net/icons/snails/sv1.ico
  - name: Server 2 | Drift/Freeroam
    url: https://sv2.heatgaming.net
    icon: https://cdn.heatgaming.net/icons/snails/sv2.ico
  - name: Server 1 | Miscellaneous 
    url: https://sv3.heatgaming.net
    icon: https://cdn.heatgaming.net/icons/snails/sv3.ico

status-website:
  cname: stats.heatgaming.net
  logoUrl: https://cdn.heatgaming.net/logos/logo_transparent-borderless.png
  favicon: https://cdn.heatgaming.net/logos/logo_transparent-borderless.png
  # themes: light, dark, night, or ocean.
  theme: night
  name: Heat Gaming
  introTitle: "**Heat Gaming Network**"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: Discord
      href: https://discord.gg/de3sXsX
  metaTags:
    # Primary Meta Tags
    - name: "title"
      content: "Heat Gaming Network Status"
    - name: "description"
      content: "View The status of any server/services, as well as incident reports and updates, with live metrics straight from the servers."
    - name: "theme-color"
      content: "#9e33c1"

# https://upptime.js.org/docs/configuration