# Change these first
owner: Heat-Gaming
repo: stats

sites:
  - name: Server 1 | Roleplay
    url: https://sv1.heatgaming.net
    icon: https://cdn.heatgaming.net/icons/snails/sv1.ico
  - name: Server 2 | Drift/Freeroam
    url: https://sv2.heatgaming.net
    icon: https://cdn.heatgaming.net/icons/snails/sv2.ico
  - name: Server 1 | Miscellaneous 
    url: https://sv3.heatgaming.net
    icon: https://cdn.heatgaming.net/icons/snails/sv3.ico

status-website:
  cname: stats.heatgaming.net
  logoUrl: https://cdn.heatgaming.net/logos/logo_transparent-borderless.ico
  name: Heat Gaming
  introTitle: "**Heat Gaming Network**"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: Discord
      href: https://discord.gg/de3sXsX

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
